import enum


class Command(enum.IntEnum):
    # 握手消息
    HANDSHAKE_REQ = 0x0101
    HANDSHAKE_RES = 0x0201

    # 光源稳定性检测
    CHECK_LIGHT_STABILITY = 0x0110
    CHECK_LIGHT_STABILITY_RES = 0x0210
    # 标准物质波长准确性检测
    CHECK_STANDARD_WAVE_ACCURACY = 0x0111
    CHECK_STANDARD_WAVE_ACCURACY_RES = 0x0211
    # 标准物质波长重复性检测
    CHECK_STANDARD_WAVE_REPEATABILITY = 0x0112
    CHECK_STANDARD_WAVE_REPEATABILITY_RES = 0x0212
    # 停止检测
    CHECK_STOP = 0x011F

    START_COLLECT = 0x10
    STOP_COLLECT = 0x11
